config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "devise/registrations" }

  root to: 'welcome#index'

  get '/', to: 'welcome#index'

  resources :roadmaps, only: :show do
    resources :nodes, only: :show
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :members
    resources :roadmaps do
      member do 
        get :ui_settings
      end
      resources :nodes
    end

    resources :assessments, only: :create, module: 'assessments' do
      resources :questions
    end
  end

  namespace :student do
    get '/', to: 'dashboard#index'
    resources :roadmaps, only: %i[index show]
  end

  namespace :assessments do
    scope path: ':assessment_id' do
      resources :attempts, only: %i[new create]
    end

    resources :attempts, only: :show do
      member do
        patch :submit
      end

      resources :questions, only: %i[index] do
        collection do
          get ':index', to: 'questions#index'
        end

        resources :answers, only: :create
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assessments.rb
# frozen_string_literal: true

module Assessments
  def self.table_name_prefix
    'assessments_'
  end
end

app/models/assessments/answer.rb
# frozen_string_literal: true

module Assessments
  class Answer < ApplicationRecord
    multi_tenant :organization

    belongs_to :question
    belongs_to :attempt, inverse_of: :answers
  end
end

app/models/checkpoint.rb
# frozen_string_literal: true

class Checkpoint < Node
end

app/models/edge.rb
# frozen_string_literal: true

class Edge < ApplicationRecord
  multi_tenant :organization

  belongs_to :source, class_name: 'Node', foreign_key: 'source_id'
  belongs_to :target, class_name: 'Node', foreign_key: 'target_id', inverse_of: :incoming_edges
end

app/models/editor.rb
class Editor < ApplicationRecord
  multi_tenant :organization

  belongs_to :user
  belongs_to :roadmap
end

app/models/maintainer.rb
# frozen_string_literal: true

class Maintainer < ApplicationRecord
  multi_tenant :organization

  belongs_to :user
  belongs_to :roadmap

  delegate :first_name, :last_name, :email, to: :user
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  multi_tenant :organization

  include Invitable

  belongs_to :organization
  belongs_to :user

  delegate :full_name, :email, to: :user
end

app/models/node.rb
# frozen_string_literal: true

class Node < ApplicationRecord
  multi_tenant :organization

  attr_accessor :child_id

  has_ancestry

  has_one_attached :blog_image

  has_rich_text :content

  belongs_to  :roadmap
  has_many    :incoming_edges,  class_name: 'Edge', foreign_key: 'target_id', dependent: :destroy, inverse_of: :target
  has_many    :outgoing_edges,  class_name: 'Edge', foreign_key: 'source_id', dependent: :destroy

  has_one     :assessment,      class_name: 'Assessments::Assessment',        dependent: :destroy

  after_initialize  :set_roadmap_id,   if: -> { new_record? && roadmap_id.nil? }
  after_initialize  :set_position,     if: -> { new_record? && position.blank? }
  after_create      :create_edge,      if: -> { incoming_edges.empty? && parent.present? }
  after_save        :update_child,     if: -> { child_id.present? }
  after_update      :update_edges,     if: -> { ancestry_changed? }

  accepts_nested_attributes_for :incoming_edges
  accepts_nested_attributes_for :assessment

  def edges
    incoming_edges.or(outgoing_edges)
  end

  private

  def update_child
    Node.find(child_id).update!(parent: self)
  end

  def update_edges
    Edge.where(target_id: id).update!(source_id: parent.id)
  end

  def set_roadmap_id
    self.roadmap_id = parent&.roadmap_id
  end

  def create_edge
    Edge.create!(source: parent, target: self, source_handle: 'bottom', target_handle: 'top')
  end

  def set_position
    self.position = {
      x: parent.present? ? parent.position['x'].to_f : 0,
      y: parent.present? ? parent.position['y'].to_f + 150 : 0
    }
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
end

app/models/roadmap.rb
# frozen_string_literal: true

class Roadmap < ApplicationRecord
  extend FriendlyId
  multi_tenant :organization

  store_accessor :ui_settings, :step_nodes, :task_nodes, :step_edges, :task_edges, suffix: :settings

  friendly_id :title, use: :slugged

  has_many :maintainers, dependent: :destroy
  has_many :nodes,       dependent: :destroy
  has_many :steps
  has_one  :creator, -> { where(is_creator: true) }, class_name: 'Maintainer'

  validates :title, presence: true

  accepts_nested_attributes_for :nodes

  after_create :create_first_node, if: -> { nodes.empty? }

  def edges
    Edge.joins(%i[source target]).where(nodes: { roadmap_id: id })
  end

  def height
    nodes.reduce(0) { |max_y, node| [max_y, node.position['y'].to_i].max }
  end

  def create_first_node
    nodes.create(type: 'Step', title: 'Step 1')
  end
end

app/models/step.rb
# frozen_string_literal: true

class Step < Node
end

app/models/task.rb
# frozen_string_literal: true

class Task < Node
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assessment_attempts, class_name: 'Assessments::Attempt'

  has_many :members

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_not_signed_up_yet?
    members.where.not(invitation_accepted_at: nil).any?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include TenantResolvable
  include Pagy::Backend

  def current_member
    Memeber.find_by(user: current_user, organization: current_tenant)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :invitable_from_invitation_token, only: [:edit, :destroy]

  def new
    @invitable = invitable_class.new
  end

  # POST /resource/invitation
  def create
    @invitable = invitable_class.invite!(invite_params, current_user)
  end

  # GET /resource/invitation/accept?invitation_token=abcdef
  def edit
    set_minimum_password_length
    @invitable.invitation_token = params[:invitation_token]
  end

  # PUT /resource/invitation
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    @invitable = invitable_class.accept_invitation!(update_resource_params)

    unless @invitable.errors.any?
      sign_in(:user, @invitable.user)
    end
  end

  # GET /resource/invitation/remove?invitation_token=abcdef
  def destroy
    @invitable.destroy
  end

  protected
    def invitable_from_invitation_token
      @invitable = invitable_class.find_by_invitation_token(params[:invitation_token], true)
    end

    def invite_params
      devise_parameter_sanitizer.sanitize(:invite)
    end

    def update_resource_params
      devise_parameter_sanitizer.sanitize(:accept_invitation)
    end

    def translation_scope
      'devise.invitations'
    end

    def invitable_class
      Member
    end
end

app/controllers/nodes_controller.rb
# frozen_string_literal: true

class NodesController < ApplicationController
  before_action :find_roadmap
  before_action :find_node

  def show; end

  private

  def find_node
    @node = @roadmap.nodes.find(params[:id])
  end

  def find_roadmap
    @roadmap = Roadmap.friendly.find(params[:roadmap_id])
  end
end

app/controllers/roadmaps_controller.rb
# frozen_string_literal: true

class RoadmapsController < ApplicationController
  before_action :find_roadmap

  # GET /roadmaps/1 or /roadmaps/1.json
  def show; end

  private

  def find_roadmap
    @roadmap = Roadmap.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Instructify
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = yield :head
  %body
    = render "shared/sidebar"
    %main
      = render "shared/header"
      .container-fluid
        = yield
        = turbo_frame_tag "modal", target: "_top"
        = turbo_frame_tag "offcanvas", target: "_top"

app/views/shared/_footer.html.haml
%footer.position-fixed.w-100.bottom-0.footer__bg.footer__bg--color
  .container
    %p.text-center.d-block.pt-3.pb-3.m-0.fw-bold.text-white @powered by Instructify 2023

app/views/shared/_header.html.haml
%header.container-fluid.d-flex.py-6.mb-4
  / Search
  %form.d-none.d-md-inline-block.me-auto
    .input-group.input-group-merge
      / Input
      %input.form-control.border-light-green.w-250px{"aria-label" => "Search for any term", :placeholder => "Search...", :type => "text"}/
      / Button
      %span.input-group-text.bg-light-green.border-light-green.p-0
        / Button
        %button.btn.btn-primary.rounded-2.w-30px.h-30px.p-0.mx-1{"aria-label" => "Search button", :type => "button"}
          %svg{:height => "16", :viewbox => "0 0 24 24", :width => "16", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M0.750 9.812 A9.063 9.063 0 1 0 18.876 9.812 A9.063 9.063 0 1 0 0.750 9.812 Z", :fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.5", :transform => "translate(-3.056 4.62) rotate(-23.025)"}
            %path{:d => "M16.221 16.22L23.25 23.25", :fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "1.5"}
  .d-flex.align-items-center.ms-auto.me-n1.me-lg-n2
    = render partial: 'shared/theme_switch'
    .vr.bg-gray-700.mx-2.mx-lg-3
    .dropdown
      %a.dropdown-toggle.no-arrow.d-flex.align-items-center.justify-content-center.bg-white.rounded-circle.shadow-sm.mx-1.mx-lg-2.w-40px.h-40px{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-offset" => "0,0", "data-bs-toggle" => "dropdown", :href => "javascript: void(0);", :role => "button"}
        %span.avatar.avatar-circle.avatar-xxs
          %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/8ab0a140561aa1ea23abaa0101bd41b9b1d0cb12/e951b/assets/images/flags/1x1/us.svg", :width => "18"}/
      %ul.dropdown-menu.dropdown-menu-end
        %li
          %h6.dropdown-header.text-uppercase Select language
        %li
          %a.dropdown-item.active{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/8ab0a140561aa1ea23abaa0101bd41b9b1d0cb12/e951b/assets/images/flags/1x1/us.svg", :width => "18"}/
            %span.text-truncate.ms-2 English (US)
        %li
          %a.dropdown-item{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/7ee571bc59a0a1ac377631263167fb273a12a7d4/f112e/assets/images/flags/1x1/gb.svg", :width => "18"}/
            %span.text-truncate.ms-2 English (UK)
        %li
          %a.dropdown-item{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/719d768eaac30c30937cb72db78ce3391e33a5dc/05fb9/assets/images/flags/1x1/es.svg", :width => "18"}/
            %span.text-truncate.ms-2 Español
        %li
          %a.dropdown-item{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/423c01c313d4dd7ca6acd49b868069981490a9b7/c7155/assets/images/flags/1x1/fr.svg", :width => "18"}/
            %span.text-truncate.ms-2 Française
        %li
          %a.dropdown-item{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/ba8ec66c54af0ff852cdbee4794d3858176ac85e/419c1/assets/images/flags/1x1/de.svg", :width => "18"}/
            %span.text-truncate.ms-2 Deutsch
        %li
          %a.dropdown-item{:href => "javascript: void(0);"}
            %span.avatar.avatar-circle.avatar-xxs
              %img.avatar-img{:alt => "...", :height => "18", :src => "https://d33wubrfki0l68.cloudfront.net/c82251ff8fa03cc4eaaa6f972e7a9eb6f3d9380c/f62a5/assets/images/flags/1x1/cn.svg", :width => "18"}/
            %span.text-truncate.ms-2 中文 (繁體)
    / Separator
    .vr.bg-gray-700.mx-2.mx-lg-3
    / Button
    %a.d-flex.align-items-center.justify-content-center.bg-white.rounded-circle.shadow-sm.mx-1.mx-lg-2.w-40px.h-40px.position-relative.link-secondary{"aria-controls" => "offcanvasNotifications", "data-bs-toggle" => "offcanvas", :href => "#offcanvasNotifications", :role => "button"}
      %i.bi.bi-bell.fs-6  
      %span.position-absolute.top-0.start-100.translate-middle.badge.rounded-pill.text-bg-danger
        20+
        %span.visually-hidden unread messages
    / Notifications offcanvas
    #offcanvasNotifications.offcanvas.offcanvas-end{"aria-labelledby" => "offcanvasNotificationsLabel", :tabindex => "-1"}
      .offcanvas-header.px-5
        %h3#offcanvasNotificationsLabel.offcanvas-title Notifications
        .d-flex.align-items-start
          .dropdown
            %a.dropdown-toggle.no-arrow.w-20px.h-20px.me-2.text-body{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "javascript: void(0);", :role => "button"}
              %svg{:height => "16", :viewbox => "0 0 24 24", :width => "16", :xmlns => "http://www.w3.org/2000/svg"}
                %g
                  %circle{:cx => "3.25", :cy => "12", :r => "3.25", :style => "fill: currentColor"}
                  %circle{:cx => "12", :cy => "12", :r => "3.25", :style => "fill: currentColor"}
                  %circle{:cx => "20.75", :cy => "12", :r => "3.25", :style => "fill: currentColor"}
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "javascript: void(0);"}
                  %svg.me-2.text-secondary{:height => "14", :viewbox => "0 0 24 24", :width => "14", :xmlns => "http://www.w3.org/2000/svg"}
                    %g
                      %path{:d => "M23.22,2.06a1.49,1.49,0,0,0-2,.59l-8.5,15.43L6.46,11.29a1.5,1.5,0,1,0-2.21,2l7.64,8.34a1.52,1.52,0,0,0,2.42-.29L23.81,4.1A1.5,1.5,0,0,0,23.22,2.06Z", :style => "fill: currentColor"}
                      %path{:d => "M2.61,14.63a1.5,1.5,0,0,0-2.22,2l4.59,5a1.52,1.52,0,0,0,2.11.09,1.49,1.49,0,0,0,.1-2.12Z", :style => "fill: currentColor"}
                      %path{:d => "M10.3,13a1.41,1.41,0,0,0,2-.54L16.89,4.1a1.5,1.5,0,1,0-2.62-1.45L9.68,11A1.41,1.41,0,0,0,10.3,13Z", :style => "fill: currentColor"}
                  Mark as all read
              %li
                %a.dropdown-item{:href => "javascript: void(0);"}
                  %svg.me-2.text-secondary{:height => "14", :viewbox => "0 0 24 24", :width => "14", :xmlns => "http://www.w3.org/2000/svg"}
                    %g
                      %path{:d => "M21.5,2.5H2.5a2,2,0,0,0-2,2v3a1,1,0,0,0,1,1h21a1,1,0,0,0,1-1v-3A2,2,0,0,0,21.5,2.5Z", :style => "fill: currentColor"}
                      %path{:d => "M21.5,10H2.5a1,1,0,0,0-1,1v8.5a2,2,0,0,0,2,2h17a2,2,0,0,0,2-2V11A1,1,0,0,0,21.5,10Zm-6.25,3.5A1.25,1.25,0,0,1,14,14.75H10a1.25,1.25,0,0,1,0-2.5h4A1.25,1.25,0,0,1,15.25,13.5Z", :style => "fill: currentColor"}
                  Archive all
              %li
                %a.dropdown-item{:href => "javascript: void(0);"}
                  %svg.me-2.text-secondary{:height => "14", :viewbox => "0 0 24 24", :width => "14", :xmlns => "http://www.w3.org/2000/svg"}
                    %g
                      %path{:d => "M21,19.5a1,1,0,0,0,0-2A1.5,1.5,0,0,1,19.5,16V11.14a8.65,8.65,0,0,0-.4-2.62l-11,11Z", :style => "fill: currentColor"}
                      %path{:d => "M14.24,21H9.76a.25.25,0,0,0-.24.22,2.64,2.64,0,0,0,0,.28,2.5,2.5,0,0,0,5,0,2.64,2.64,0,0,0,0-.28A.25.25,0,0,0,14.24,21Z", :style => "fill: currentColor"}
                      %path{:d => "M1,24a1,1,0,0,0,.71-.28l22-22a1,1,0,0,0,0-1.42,1,1,0,0,0-1.42,0l-5,5A7.31,7.31,0,0,0,13,3.07V1a1,1,0,0,0-2,0V3.07a8,8,0,0,0-6.5,8.07V16A1.5,1.5,0,0,1,3,17.5a1,1,0,0,0,0,2h.09L.29,22.29a1,1,0,0,0,0,1.42A1,1,0,0,0,1,24Z", :style => "fill: currentColor"}
                  Disable notifications
              %li
                %hr.dropdown-divider/
              %li
                %a.dropdown-item{:href => "javascript: void(0);"}
                  %svg.me-2.text-secondary{:height => "14", :viewbox => "0 0 24 24", :width => "14", :xmlns => "http://www.w3.org/2000/svg"}
                    %g
                      %rect{:height => "7.25", :rx => "1.25", :style => "fill: currentColor", :width => "5.75", :x => "4.25", :y => "4.5"}
                      %path{:d => "M24,10a3,3,0,0,0-3-3H19V2.5a2,2,0,0,0-2-2H2a2,2,0,0,0-2,2V20a3.5,3.5,0,0,0,3.5,3.5h17A3.5,3.5,0,0,0,24,20ZM3.5,21.5A1.5,1.5,0,0,1,2,20V3a.5.5,0,0,1,.5-.5h14A.5.5,0,0,1,17,3V20a3.51,3.51,0,0,0,.11.87.5.5,0,0,1-.09.44.49.49,0,0,1-.39.19ZM22,20a1.5,1.5,0,0,1-3,0V9.5a.5.5,0,0,1,.5-.5H21a1,1,0,0,1,1,1Z", :style => "fill: currentColor"}
                      %rect{:height => "2", :rx => "0.75", :style => "fill: currentColor", :width => "3.5", :x => "12", :y => "6.05"}
                      %rect{:height => "2", :rx => "0.75", :style => "fill: currentColor", :width => "3.5", :x => "12", :y => "10.05"}
                      %rect{:height => "2", :rx => "0.75", :style => "fill: currentColor", :width => "11.5", :x => "4", :y => "14.05"}
                      %rect{:height => "2", :rx => "0.75", :style => "fill: currentColor", :width => "9", :x => "4", :y => "18.05"}
                  What's new?
          / Button
          %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "offcanvas", :type => "button"}
      .offcanvas-body.p-0
        .list-group.list-group-flush
          %a.list-group-item.list-group-item-action{:href => "javascript: void(0);"}
            .d-flex
              .avatar.avatar-circle.avatar-xs.me-2
                %img.avatar-img{:alt => "...", :height => "30", :src => "https://d33wubrfki0l68.cloudfront.net/5dfa4398a7f2beddbcfa617402e193f2f13aaa94/2ecb0/assets/images/profiles/profile-28.jpeg", :width => "30"}/
              .d-flex.flex-column.flex-grow-1
                .d-flex.w-100.justify-content-between
                  %h5.mb-1 Daniel
                  %small.text-muted 10 minutes ago
                .d-flex.flex-column
                  %p.mb-1 RE: Email pre-population from external source
                  %small.text-secondary Not sure if we'll need any further instruction on how to utilise the encoded ID in links from the new email broadcast tool.

    .vr.bg-gray-700.mx-2.mx-lg-3
    / Dropdown
    .dropdown
      %a.dropdown-toggle.no-arrow.d-flex.align-items-center.justify-content-center.bg-white.rounded-circle.shadow-sm.mx-1.mx-lg-2.w-40px.h-40px{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-auto-close" => "outside", "data-bs-offset" => "0,0", "data-bs-toggle" => "dropdown", :href => "javascript: void(0);", :role => "button"}
        .avatar.avatar-circle.avatar-sm.avatar-online{:cursorshover => "true"}
          %img.avatar-img{:alt => "...", :height => "40", :src => "https://d33wubrfki0l68.cloudfront.net/053f2dfd0df2f52c41e903a21d177b0b44abc9b1/1282c/assets/images/profiles/profile-06.jpeg", :width => "40"}/
      .dropdown-menu
        .dropdown-item-text
          .d-flex.align-items-center
            .avatar.avatar-sm.avatar-circle
              %img.avatar-img{:alt => "...", :height => "40", :src => "https://d33wubrfki0l68.cloudfront.net/053f2dfd0df2f52c41e903a21d177b0b44abc9b1/1282c/assets/images/profiles/profile-06.jpeg", :width => "40"}/
            .flex-grow-1.ms-3
              %h4.mb-0 Ellie Tucker
              %p.card-text ellie.tucker@dashly.com
        %hr.dropdown-divider/
        / Dropdown
        .dropdown.dropend
          %a#statusDropdown.dropdown-item.dropdown-toggle{"aria-expanded" => "false", "data-bs-offset" => "-16,10", "data-bs-toggle" => "dropdown", :href => "javascript: void(0);"}
            Set status
          .dropdown-menu.dropdown-menu-end.navbar-dropdown-menu.navbar-dropdown-menu-borderless.navbar-dropdown-sub-menu{"aria-labelledby" => "statusDropdown"}
            %a.dropdown-item{:href => "javascript: void(0);"}
              %span.legend-circle.bg-success.me-2>
              Available
            %a.dropdown-item{:href => "javascript: void(0);"}
              %span.legend-circle.bg-danger.me-2>
              Busy
            %a.dropdown-item{:href => "javascript: void(0);"}
              %span.legend-circle.bg-warning.me-2>
              Away
            %a.dropdown-item{:href => "javascript: void(0);"}
              %span.legend-circle.bg-gray-500.me-2>
              Appear offline
            %hr.dropdown-divider/
            %a.dropdown-item{:href => "javascript: void(0);"}
              Reset status
        / End Dropdown
        %a.dropdown-item{:href => "javascript: void(0);"} Profile &amp; account
        %a.dropdown-item{:href => "javascript: void(0);"} Settings
        %hr.dropdown-divider/
        = link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete  }, class: "dropdown-item"

app/views/shared/_sidebar.html.haml
%nav#mainNavbar.navbar.navbar-vertical.navbar-expand-lg.scrollbar.bg-dark.navbar-dark
  :javascript
    var navigationColor = localStorage.getItem('navigationColor'),
        navbar = document.getElementById('mainNavbar');
                
    if(navigationColor != null && navbar != null) {
        if(navigationColor == 'inverted') {
            navbar.classList.add('bg-dark', 'navbar-dark');
            navbar.classList.remove('bg-white', 'navbar-light');
        } else {
            navbar.classList.add('bg-white', 'navbar-light');
            navbar.classList.remove('bg-dark', 'navbar-dark');
        }
    }
  .container-fluid
    %a.navbar-brand{:href => "./index.html"}
      %h2 instructify
    %a.navbar-toggler{"aria-controls" => "sidenavCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#sidenavCollapse", "data-bs-toggle" => "collapse", :href => "javascript: void(0);"}
      %span.navbar-toggler-icon
    #sidenavCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mb-lg-7
        %li.nav-item.dropdown
          = link_to admin_path, class: 'nav-link' do
            %i.bi.bi-house.nav-link-icon.fs-6
            %span Dashboards
        %li.nav-item
          = link_to admin_roadmaps_path, class: 'nav-link' do
            %i.bi.bi-bar-chart-steps.nav-link-icon.fs-6
            %span Roadmaps
        %li.nav-item.dropdown
          %a.nav-link{"aria-controls" => "dashboardsCollapse", "aria-expanded" => "false", "data-bs-toggle" => "collapse", :href => "#dashboardsCollapse", :role => "button"}
            %i.bi.bi-people.nav-link-icon.fs-6
            %span Users
          #dashboardsCollapse.collapse
            %ul.nav.flex-column
              %li.nav-item
                = link_to admin_members_path(role: 'admin'), class: 'nav-link' do
                  %span Admins
              %li.nav-item
                = link_to admin_members_path(role: 'teacher'), class: 'nav-link' do
                  %span Teachers
              %li.nav-item
                = link_to admin_members_path(role: 'student'), class: 'nav-link' do
                  %span Students
  