config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "devise/registrations" }

  root to: 'welcome#index'

  get '/', to: 'welcome#index'

  resources :roadmaps, only: :show do
    resources :nodes, only: :show
  end

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :members
    resources :roadmaps do
      member do 
        get :ui_settings
      end
      resources :nodes
    end

    resources :assessments, only: :create, module: 'assessments' do
      resources :questions
    end
  end

  namespace :student do
    get '/', to: 'dashboard#index'
    resources :roadmaps, only: %i[index show]
  end

  namespace :assessments do
    scope path: ':assessment_id' do
      resources :attempts, only: %i[new create]
    end

    resources :attempts, only: :show do
      member do
        patch :submit
      end

      resources :questions, only: %i[index] do
        collection do
          get ':index', to: 'questions#index'
        end

        resources :answers, only: :create
      end
    end
  end
end

app/models/assessments.rb
# frozen_string_literal: true

module Assessments
  def self.table_name_prefix
    'assessments_'
  end
end

app/models/assessments/answer.rb
# frozen_string_literal: true

module Assessments
  class Answer < ApplicationRecord
    multi_tenant :organization

    belongs_to :question
    belongs_to :attempt, inverse_of: :answers
  end
end

app/models/assessments/answer_option.rb
# frozen_string_literal: true

module Assessments
  class AnswerOption
    include ActiveModel::Model

    attr_accessor :index, :value, :_destroy

    def marked_for_destruction?
      false
    end

    def [](key)
      instance_variable_get("@#{key}")
    end

    def []=(key, value)
      instance_variable_set("@#{key}", value)
    end
  end
end

app/models/assessments/assessment.rb
# frozen_string_literal: true

module Assessments
  class Assessment < ApplicationRecord
    multi_tenant :organization

    has_many    :attempts, dependent: :destroy
    has_many    :questions, dependent: :destroy

    belongs_to  :node

    accepts_nested_attributes_for :questions, allow_destroy: true
  end
end

app/models/assessments/attempt.rb
# frozen_string_literal: true

module Assessments
  class Attempt < ApplicationRecord
    multi_tenant :organization

    belongs_to :assessment
    belongs_to :user

    has_many   :questions, through: :assessment
    has_many   :answers, inverse_of: :attempt, autosave: true

    def submit
      update(submitted_at: Time.zone.now)
    end

    def submitted?
      submitted_at.present?
    end
  end
end

app/models/assessments/question.rb
# frozen_string_literal: true

module Assessments
  class Question < ApplicationRecord
    multi_tenant :organization

    belongs_to :assessment, inverse_of: :questions
    has_many   :answers

    def self.pretty_name
      name.split('::').last.underscore.humanize
    end
  end
end

app/models/assessments/questions/long_text.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class LongText < Assessments::Question
    end
  end
end

app/models/assessments/questions/multiple_choice.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class MultipleChoice < Assessments::Question
      acts_as_has_many :answer_options, class_name: 'Assessments::AnswerOption'
      acts_as_accepts_nested_attributes_for :answer_options
    end
  end
end

app/models/assessments/questions/numeric.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class Numeric < Assessments::Question
    end
  end
end

app/models/assessments/questions/select.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class Select < Assessments::Question
    end
  end
end

app/models/assessments/questions/single_choice.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class SingleChoice < Assessments::Question
      acts_as_has_many :answer_options, class_name: 'Assessments::AnswerOption'
      acts_as_accepts_nested_attributes_for :answer_options
    end
  end
end

app/models/assessments/questions/text.rb
# frozen_string_literal: true

module Assessments
  module Questions
    class Text < Assessments::Question
    end
  end
end

app/controllers/admin/assessments/assessments_controller.rb
# frozen_string_literal: true

module Admin
  module Assessments
    class AssessmentsController < ApplicationController
      def create
        @assessment = Assessments::Assessment.create(assessment_params)

        respond_to do |format|
          if @assessment.save
            format.turbo_stream
            format.html { redirect_to assessments_questions_path(assessment_id: @assessment.id) }
          end
        end
      end

      def assessment_params
        params.require(:assessment).permit(:node_id)
      end
    end
  end
end

app/controllers/admin/assessments/questions_controller.rb
# frozen_string_literal: true

module Admin
  module Assessments
    class QuestionsController < Admin::ApplicationController
      before_action :find_assessment!
      before_action :find_question!, only: %i[edit update destroy]

      def index
        @questions = @assessment.questions
      end

      def new
        @question = @assessment.questions.build(type: params[:type])
      end

      def edit; end

      def create
        @question = @assessment.questions.build(question_params)
        respond_to do |format|
          if @question.save
            format.turbo_stream
            format.html { redirect_to assessments_questions_path, notice: 'Question Added' }
          end
        end
      end

      def update
        respond_to do |format|
          if @question.update(question_params)
            format.turbo_stream
            format.html { redirect_to assessments_questions_path, notice: 'Question Added' }
          end
        end
      end

      def destroy
        respond_to do |format|
          if @question.destroy
            format.turbo_stream
            format.html { redirect_to assessments_questions_path, notice: 'Question Rermoved' }
          end
        end
      end

      private

      def question_params
        params.require(:question).permit(:type, :content, :correct_answer,
                                         answer_options_attributes: %i[index value _destroy])
      end

      def find_question!
        @question = @assessment.questions.find(params[:id])
      end

      def find_assessment!
        @assessment = Assessments::Assessment.find(params[:assessment_id])
      end
    end
  end
end

app/controllers/assessments/answers_controller.rb
# frozen_string_literal: true

module Assessments
  class AnswersController < ApplicationController
    before_action :authenticate_user!
    before_action :find_attempt!
    before_action :find_question!
    before_action :find_or_initialize_answer

    def create
      @answer.update(content: answer_params[:content])
    end

    private

    def find_attempt!
      @attempt = current_user.assessment_attempts.find(params[:attempt_id])
    end

    def find_question!
      @question = @attempt.assessment.questions.find(params[:question_id])
    end

    def find_or_initialize_answer
      @answer = @attempt.answers.find_or_initialize_by(question: @question)
    end

    def answer_params
      params.require(:answer)
    end
  end
end

app/controllers/assessments/attempts_controller.rb
# frozen_string_literal: true

module Assessments
  class AttemptsController < ApplicationController
    before_action :authenticate_user!, except: :new
    before_action :find_assessment!, only: %i[new create]
    before_action :find_attempt!, only: %i[show submit]

    def new
      return unless user_signed_in?

      @attempt = @assessment.attempts.new(user: current_user)
    end

    def create
      @attempt = @assessment.attempts.new(user: current_user)

      if @attempt.save
        redirect_to assessments_attempt_questions_path(attempt_id: @attempt), notice: 'Assessment Started'
      else
        render :new
      end
    end

    def show
      unless @attempt.submitted?
        return redirect_to assessments_attempt_questions_path(attempt_id: @attempt),
                           notice: 'Assessment not completed'
      end

      @answers = @attempt.answers
    end

    def submit
      return unless @attempt.submit

      redirect_to assessments_attempt_path(@attempt), notice: 'Assessment Submitted'
    end

    private

    def find_assessment!
      @assessment = Assessments::Assessment.find(params[:assessment_id])
    end

    def find_attempt!
      @attempt = current_user.assessment_attempts.find_by!(id: params[:id])
    end
  end
end

app/controllers/assessments/questions_controller.rb
# frozen_string_literal: true

module Assessments
  class QuestionsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_attempt!
    before_action :ensure_attempt_not_submitted

    helper_method :pagy_url_for

    def index
      @pagy, @questions = pagy(
        @attempt.questions,
        size: [],
        page_param: :index,
        page: params[:index] || 1,
        items: params[:index].present? ? 1 : 1000
      )
    end

    private

    def pagy_url_for(pagy, page, absolute: false, html_escaped: false)
      params = request.query_parameters.merge(pagy.vars[:page_param] => page, only_path: !absolute)
      html_escaped ? url_for(params).gsub('&', '&amp;') : url_for(params)
    end

    def find_attempt!
      @attempt = current_user.assessment_attempts.find(params[:attempt_id])
    end

    def ensure_attempt_not_submitted
      redirect_to assessments_attempt_path(@attempt), notice: 'Assessment Submitted' and return if @attempt.submitted?
    end
  end
end

app/helpers/admin/assessments/assessments_helper.rb
# frozen_string_literal: true

module Admin
  module Assessments
    module AssessmentsHelper
    end
  end
end

app/helpers/admin/assessments/questions_helper.rb
# frozen_string_literal: true

module Admin
  module Assessments
    module QuestionsHelper
    end
  end
end

app/helpers/assessments/answers_helper.rb
# frozen_string_literal: true

module Assessments
  module AnswersHelper
  end
end

app/views/admin/assessments/questions/_answer_option_form.html.haml
.nested-form-wrapper
  .d-flex
    = f.text_field :value, class: 'form-control mb-2'
    %a.btn.btn-link.text-danger{ data: { action: "nested-form#remove" }}
      %i.bi.bi-trash
  = f.hidden_field :_destroy

app/views/admin/assessments/questions/_form.html.haml
- url = question.persisted? ? admin_assessment_question_path : admin_assessment_questions_path
= form_for question, as: :question, url: url do |f|
  = f.hidden_field :type
  .form-group
    = f.label :content, class: "form-label"
    = f.text_area :content, class: 'form-control mb-3'
  
  - if question.is_a?(Assessments::Questions::MultipleChoice) || question.is_a?(Assessments::Questions::SingleChoice)
    .form-group.mb-2
      = f.label 'Options'
    %div{data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }}  
      %template{"data-nested-form-target" => "template"}
        = f.fields_for :answer_options, Assessments::AnswerOption.new, child_index: 'NEW_RECORD' do |ff|
          = render 'answer_option_form', f: ff
      = f.fields_for :answer_options, question.answer_options do |ff|
        = render 'answer_option_form', f: ff
      %div{"data-nested-form-target" => "target"}
      %button.btn.btn-outline-primary.w-100{"data-action" => "nested-form#add", type: "button"} Add Option
      
  = f.submit "Save", class: "btn btn-success btn-block"

app/views/admin/assessments/questions/_index.html.haml
= turbo_frame_tag 'questions-container' do
  #questions
    - questions.each do |question|
      = render 'admin/assessments/questions/question', question: question
  = link_to 'Add new Question', new_admin_assessment_question_path(assessment_id: assessment.id), data: { turbo_frame: "modal" }, class: 'btn btn-outline-primary w-100'

app/views/admin/assessments/questions/_question.html.haml
= turbo_frame_tag dom_id(question) do
  .card
    .card-body.mb-3
      %small.badge.text-bg-primary.mb-2
        = question.class.pretty_name
      .card-title.d-flex.justify-content-between
        = question.content
        .actions
          = link_to edit_admin_assessment_question_path(id: question, assessment_id: question.assessment_id), data: { turbo_frame: "modal" }, class: 'btn btn-link' do
            %i.bi.bi-pen
          = link_to admin_assessment_question_path(id: question, assessment_id: question.assessment_id), method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-link text-danger' do
            %i.bi.bi-trash
      .card-text
        - if question.is_a?(Assessments::Questions::MultipleChoice) || question.is_a?(Assessments::Questions::SingleChoice)
          %ul
            - question.answer_options.each do |option|
              %li
                = option['value']
            

app/views/admin/assessments/questions/create.turbo_stream.haml
= turbo_stream.append "questions" do
  = render "question", question: @question

app/views/admin/assessments/questions/destroy.turbo_stream.haml
= turbo_stream.remove dom_id(@question)

app/views/admin/assessments/questions/edit.html.haml
= render "shared/modal", title: "Edit Question" do
  = render "form", question: @question 

app/views/admin/assessments/questions/index.html.haml
.container
  %h1 Assessment
  = render 'index', assessment: @assessment, questions: @questions

app/views/admin/assessments/questions/new.html.haml
= render "shared/modal", title: "New Question" do
  = turbo_frame_tag 'new-question-form' do
    - if params[:type]
      = render "form", question: @question
    - else
      - Assessments::Question.descendants.each do |klass|
        = link_to klass.pretty_name, new_admin_assessment_question_path(assessment_id: @assessment.id, type: klass.name), data: { turbo_frame: 'new-question-form' }, method: :get, class: 'btn btn-outline-primary w-100 d-block mb-3'

app/views/admin/assessments/questions/update.turbo_stream.haml
= turbo_stream.replace dom_id(@question) do
  = render "question", question: @question